### PR TITLE
[proposal] SE0001 Use compact syntax

### PR DESCRIPTION
**Pull request by thewillyhuman**
This PR adds a proposal to use compact syntax for shex-lite.

### CODE REVIEW

**Review by alejgh — APPROVED** [review]

**Review by DaniFdezAlvarez — APPROVED** [review]

**Comment by alejgh** [comment]
Although the compact syntax is more human friendly, a json-LD syntax needs to be supported too for machine processing.

I'm still not sure about which one should be the base syntax.

**Comment by thewillyhuman** [comment]
Hi @alejgh, I imagine that you mean that almost everyone does not say all languages ​​have libraries to process JSON right?

It seems reasonable. However, one of the premises of the language is that it is as fast as possible and if I have to use JSON as an intermediate code within my compiler the system will slow down a bit. What do you think if in the future we make an implementation of shex-lite in json-ld instead of it being common?


I think we face the basic problem of speed vs. generality.

**Comment by alejgh** [comment]
> Hi @alejgh, I imagine that you mean that almost everyone does not say all languages ​​have libraries to process JSON right?
> 
> It seems reasonable. However, one of the premises of the language is that it is as fast as possible and if I have to use JSON as an intermediate code within my compiler the system will slow down a bit. What do you think if in the future we make an implementation of shex-lite in json-ld instead of it being common?
> 
> I think we face the basic problem of speed vs. generality.

I totally agree that there could be a performance overhead, and one of the main qualities of shexlite should be its performance. It would be important to first estimate the potential decrease in performance, and then make the final decision.

**Comment by thewillyhuman** [comment]
> 
> 
> > Hi @alejgh, I imagine that you mean that almost everyone does not say all languages ​​have libraries to process JSON right?
> > It seems reasonable. However, one of the premises of the language is that it is as fast as possible and if I have to use JSON as an intermediate code within my compiler the system will slow down a bit. What do you think if in the future we make an implementation of shex-lite in json-ld instead of it being common?
> > I think we face the basic problem of speed vs. generality.
> 
> I totally agree that there could be a performance overhead, and one of the main qualities of shexlite should be its performance. It would be important to first estimate the potential decrease in performance, and then make the final decision.

Yes, I would be cool. However, it occurs to me that if for example we want to make the shex-lite error system very good, the current ast has a line and a column, this could be an inconvenience for ShExJ's automatic serialization, since in a JSON it is a graph and there is no line / column.

**Comment by alejgh** [comment]
@labra

**Comment by DaniFdezAlvarez** [comment]
Hmm I'm not sure whether I am getting this well. But if you want to keep line and column with a JSON input, maybe we should implement an ad-hoc JSON parser instead of using standard libraries. Maybe using the same framework that you used for the compact syntax, so you can generate a similar AST that knows in which place of the original JSON file there was an error (a ShEx one, not just a JSON compliance one).  JSON is a graph, but so is ShExC. The elements once parsed are not sorted, right? The line/column just refer to a position in a file

**Comment by thewillyhuman** [comment]
> 
> 
> Hmm I'm not sure whether I am getting this well. But if you want to keep line and column with a JSON input, maybe we should implement an ad-hoc JSON parser instead of using standard libraries. Maybe using the same framework that you used for the compact syntax, so you can generate a similar AST that knows in which place of the original JSON file there was an error (a ShEx one, not just a JSON compliance one). JSON is a graph, but so is ShExC. The elements once parsed are not sorted, right? The line/column just refer to a position in a file

Yes, we (@alejgh and I) think that's the ideal solution. But at the same time we have some considerations about implementing it for the very first version or for future ones. What do you think?

**Comment by DaniFdezAlvarez** [comment]
Yep, I have the very same concerns. So I'd pick ShExC for the first version. It's a reasonable choice anyway, and you have more work done in that line anyway. And once it's done you could go for the JSON one with full support to the error system

**Comment by thewillyhuman** [comment]
I talked to @labra and he uses the same style, he has two parsers one for ShExJ and one for ShExC. So there is no problem.

**Pull request merged**
