### PR TITLE
[proposal] SE0010 Disable prefix redefinitions

### PR DESCRIPTION
**Pull request by thewillyhuman**
While doing semantic validation appears this doubt and two options emerge, you can check the rendered proposal [here](https://github.com/thewilly/shex-lite-evolution/blob/0010-disable-prefix-redefinition/proposals/0010-disable-prefix-redefinition.md).

Any ideas / comments will be welcome!

### CODE REVIEW

**Comment by alejgh** [comment]
I really like the first solution, and IMO is the most intuitive to me. It is the one used in shex too.

**Comment by alejgh** [comment]
Maybe throw a warning in similar situations to the example you mentioned in the proposal?
```
prefix a: <a>

a:User .		# Resolves to <a#User>

prefix a: <b>

a:User .		# Resolves to <b#User>
```

**Comment by thewillyhuman** [comment]
> 
> 
> Maybe throw a warning in similar situations to the example you mentioned in the proposal?
> 
> ```
> prefix a: <a>
> 
> a:User .		# Resolves to <a#User>
> 
> prefix a: <b>
> 
> a:User .		# Resolves to <b#User>
> ```

So if I understand correctly you'r saying that we allow to use prefix redefinition but whenever used we generate a warning isn't it?

Therefore a plocy like this should work:
1) A prefix must be allways declared before being used, else an error is generated.
2) Prefixes can be redefined, but this generates a warning.


I'm not quite fan of this solution because with shapes works the other way (like example 2 of the proposal), for example the directive `start` (`start = @:User`) makes reference to a shape that can be defined at any point of the sources and errors are generated if the shape doesn't exists in the sources or is redefined... I would like to apply the same policy to everything in order to have something coherent.

**Comment by alejgh** [comment]
We should send an issue to them about the shapes redefinition. In my opinion both prefixes and shapes definitions should work like option one of this proposal, but thats just my opinion.
It feels more intuitive to me at least.

**Comment by alejgh** [comment]
What makes more sense to you when it comes to implementation details?

**Comment by thewillyhuman** [comment]
shapes redefinition should be completely disabled and forbidden, it does not add any functionality as the only definition that counts for validation is the last one. Redefining a shape would increase errors and reduce the safety of the language. And same applies for prefix redefinition. I agree that in the case of prefixes there is functionality attached to this because redefine a prefix allows to to change the iri associated with a label and reuse the label, but, in my opinion, as prefix labels should be semantic related to their iri redefinition also reduces language safety.

I would disable all kinds of redefinition.

**Comment by alejgh** [comment]
Ok.

**Review by alejgh — APPROVED** [review]

**Comment by DaniFdezAlvarez** [comment]
I agree with @thewilly . I see more cons than pros allowing prefix redefinition. The main pro is that ShEx allows it. On the other hand, I think that prefix redefinition could be used by accident (maybe a copypaste) causing unexpected errors. I think you should have a very strong and rare reason to use consciously the very same prefix to refer to different URIs within a single file. I feel like most of the time a prefix conflict may be caused not for that reason, but maybe a wrong copypaste of content, a small typo, etc.   As a developer, I'd prefer to have a warning detecting that situation rather than the power to change the meaning of a prefix.

Also, @thewilly will know better than me, but I think the implementation could be simpler if you just don't allow prefix redefinition, right? (Or you allow it, but the valid value that applies to the whole file is always the last declared one).

I do picture a case at least in which maybe prefix redefinition could be interesting: shapes in streaming.
I can imagine a given agent generating a stream of shapes in waves. And each wave could easily consist of some prefix definitions and then some shapes. Or maybe, due to implementation details, every received shape is preceded by the prefix definitions that it is using (which may redefine or commonly redeclare old ones). In such a scenario, I'd say it makes sense that, in case of prefix conflict, new prefixes could overwrite old ones... but even with this, I'm not sure about supporting redefinition.

**Comment by thewillyhuman** [comment]
After the meeting held by the core team, it is decided that for now the policy to be applied will be as follows:

To maintain the integrity of the language, no re-definition will be allowed. At least for the moment. In this way, when a redefinition is found, the user will be informed that he is performing an action not allowed by means of an error.

Likewise, and in order not to conflict with prefixes defined in other source files that are related by means of the import directive, it is agreed that each prefix is ​​identified atomically by the name of its source file, its line and its column.

**Pull request merged**
